name: Skyolympus
version: 0.2
main: com.skyost.olympia.Skyolympus
author: Skyost
website: http://www.skyost.eu
commands:
 olympmod:
  aliases: [olympe, olympus, olympe-mod, olympus-mod]
  description: Enable the Olympmod.
  usage: /olympmod for enable the Olympmod.
  permission: olympmod.realgodmode
permissions:
  olympmod.realgodmode:
   default: op
   description: Allow you to use the Olympmod.